// <auto-generated />
using System;
using EFCore.AIGS.UUID;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EFCore.AIGS.UUID.Migrations
{
    [DbContext(typeof(UuidContext))]
    [Migration("20220612111856_init2")]
    partial class init2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0-preview.4.22229.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "uuid-ossp");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EFCore.AIGS.UUID.Entity.ItemGroup", b =>
                {
                    b.Property<Guid?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("TEST UUID")
                        .HasColumnName("name");

                    b.Property<bool>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_item_group");

                    b.ToTable("item_group", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("d40e315c-06ac-4eb4-a66b-e78a8bbdd0d3"),
                            Name = "Cake",
                            Status = false
                        });
                });

            modelBuilder.Entity("EFCore.AIGS.UUID.Entity.ItemGroup", b =>
                {
                    b.OwnsMany("EFCore.AIGS.UUID.Entity.Item", "Items", b1 =>
                        {
                            b1.Property<Guid?>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid")
                                .HasColumnName("id")
                                .HasDefaultValueSql("gen_random_uuid()");

                            b1.Property<Guid?>("ItemGroupId")
                                .HasColumnType("uuid")
                                .HasColumnName("item_group_id");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .ValueGeneratedOnAdd()
                                .HasColumnType("text")
                                .HasDefaultValue("Item TEST")
                                .HasColumnName("name");

                            b1.Property<bool>("Status")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("boolean")
                                .HasDefaultValue(true)
                                .HasColumnName("status");

                            b1.HasKey("Id")
                                .HasName("pk_item");

                            b1.HasIndex("ItemGroupId")
                                .HasDatabaseName("ix_item_item_group_id");

                            b1.ToTable("item", (string)null);

                            b1.WithOwner("ItemGroup")
                                .HasForeignKey("ItemGroupId")
                                .HasConstraintName("fk_item_item_group_item_group_id");

                            b1.Navigation("ItemGroup");

                            b1.HasData(
                                new
                                {
                                    Id = new Guid("9747ba54-88fe-46ed-bcaa-f874ff7af56d"),
                                    ItemGroupId = new Guid("d40e315c-06ac-4eb4-a66b-e78a8bbdd0d3"),
                                    Name = "HDB cake",
                                    Status = false
                                });
                        });

                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
