// <auto-generated />
using System;
using EFCoreAIGS.V7;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EFCoreAIGS.V7.Migrations
{
    [DbContext(typeof(V7Context))]
    partial class V7ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.6");

            modelBuilder.Entity("EFCoreAIGS.V7.Model.Item", b =>
                {
                    b.Property<Guid?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ItemGroupId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("Item TEST");

                    b.Property<bool>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.HasKey("Id");

                    b.HasIndex("ItemGroupId");

                    b.ToTable("Item");

                    b.HasData(
                        new
                        {
                            Id = new Guid("95254799-131c-43a9-88c8-39865a39e61c"),
                            ItemGroupId = new Guid("d40e315c-06ac-4eb4-a66b-e78a8bbdd0d1"),
                            Name = "Milk tea",
                            Status = false
                        },
                        new
                        {
                            Id = new Guid("b2cc35e8-ed6e-4b24-a793-726844cf52d7"),
                            ItemGroupId = new Guid("d40e315c-06ac-4eb4-a66b-e78a8bbdd0d1"),
                            Name = "Ice Coffee",
                            Status = false
                        });
                });

            modelBuilder.Entity("EFCoreAIGS.V7.Model.ItemGroup", b =>
                {
                    b.Property<Guid?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("TEST UUID");

                    b.Property<bool>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.HasKey("Id");

                    b.ToTable("ItemGroup");

                    b.HasData(
                        new
                        {
                            Id = new Guid("d40e315c-06ac-4eb4-a66b-e78a8bbdd0d1"),
                            Name = "Drink",
                            Status = false
                        },
                        new
                        {
                            Id = new Guid("d40e315c-06ac-4eb4-a66b-e78a8bbdd0d2"),
                            Name = "TEST-1",
                            Status = false
                        });
                });

            modelBuilder.Entity("EFCoreAIGS.V7.Model.Item", b =>
                {
                    b.HasOne("EFCoreAIGS.V7.Model.ItemGroup", "ItemGroup")
                        .WithMany()
                        .HasForeignKey("ItemGroupId");

                    b.Navigation("ItemGroup");
                });
#pragma warning restore 612, 618
        }
    }
}
